### ISSUE TITLE
error on shift+r-click

### ISSUE THREAD

**Issue by AcesGamingUK** [JoelGodOfwar/VillagerWorkstationHighlights#2]
### Versions
Server Version `git-Paper-184 (MC:1.16.2)`
Plugin Version `1.14.1_1.0.2`

### Player Interact Error
<details>
  <summary>Config</summary>
  
  ```json
# DO NOT CHANGE VERSION
version: 1.0.2
# Change to false to stop auto-update-check.
auto_update_check: true

# Set to true before sending a log about an issue.
# Logs trace data required to pinpoint where errors are.
debug: false

# Particle Configs
particle:
  display: true
  name: HEART
  duration: 200

# Shift Right Click
shift_click:
# Set to false to not require item at all.
  require_item: true
# Set to false to use custom Material.
# Works with any workstation.
  require_workstation: false
# If require_workstation is true this will be ignored.
  required_material: minecraft:arrow
  ```
  
</details>

<details>
  <summary>Console Error</summary>
   
  ```css
  05.09 22:27:12 [Server] ERROR Could not pass event PlayerInteractEntityEvent to VillagerWorkstationHighlights v1.14.1_1.0.2
05.09 22:27:12 [Server] INFO java.lang.IllegalArgumentException: Material cannot be null
05.09 22:27:12 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at com.github.joelgodofwar.vwh.VillagerWorkstationHighlights.onPlayerInteractEvent(VillagerWorkstationHighlights.java:366) ~[?:?]
05.09 22:27:12 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor140.execute(Unknown Source) ~[?:?]
05.09 22:27:12 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2077) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:12 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
05.09 22:27:15 [Server] ERROR Could not pass event PlayerInteractEntityEvent to VillagerWorkstationHighlights v1.14.1_1.0.2
05.09 22:27:15 [Server] INFO java.lang.IllegalArgumentException: Material cannot be null
05.09 22:27:15 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at com.github.joelgodofwar.vwh.VillagerWorkstationHighlights.onPlayerInteractEvent(VillagerWorkstationHighlights.java:366) ~[?:?]
05.09 22:27:15 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor140.execute(Unknown Source) ~[?:?]
05.09 22:27:15 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2077) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-162]
05.09 22:27:15 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-162]
  ```
  
</details>

also a reload command would be SUPER helpful

**Comment by JoelGodOfwar** [comment]
Where you shift right clicking with an arrow in your hand? Based on your config settings that is the item required to make the plugin work.

**Comment by JoelGodOfwar** [comment]
Please join me on my discord server for faster responses. https://discord.gg/PXN4bzT

**Comment by AcesGamingUK** [comment]
yes i tried it with the arrow and got that error 
setting both 
`require_item: true` and `require_workstation: true` to `false`
prevents to error and works with shift r-click- have not tested with other items as restarting the server each and every time to update the config is tedious

**Comment by JoelGodOfwar** [comment]
I have a fix that corrects this error an includes /vwh reload, which can be used by players and console. It's in the dev-builds section for VWH on my discord server.

**Comment by AcesGamingUK** [comment]
seems to have fixed the issue, 
also many thanks on a reload command <3
